dsa

diff --git a/test_cases/tasks/03_task/14~ b/test_cases/tasks/03_task/14~
--- a/test_cases/tasks/03_task/14~
+++ b/test_cases/tasks/03_task/14~
@@ -1,22 +1,14 @@
 #!/bin/bash
 echo -e "=====\nTesting case $1"
-command="/bin/ls"
-
-touch tmpfile
-mv hsh ot
-OLDPATH="$PATH"
-PATH=""
+command="ls"
 
 echo -e "cheking input:\n${command}\n"
-echo "$PATH"
-echo $command | sh > "tasks/03_task/log${1}/esp" 2> "tasks/03_task/log${1}/esp_error"
-excod1=$?
-echo "$PATH"
-echo $command | hsh > "tasks/03_task/log${1}/out" 2> "tasks/03_task/log${1}/out_error"
-excod2=$?
-PATH="$OLDPATH"
 
-mv ot hsh
+echo "$command" | sh > "tasks/03_task/log${1}/esp" 2> "tasks/03_task/log${1}/esp_error"
+excod1=$?
+echo "$command" | ./hsh > "tasks/03_task/log${1}/out" 2> "tasks/03_task/log${1}/out_error"
+excod2=$?
+
 if ! diff "tasks/03_task/log${1}/out" "tasks/03_task/log${1}/esp"
    then
     ./fail
